//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DX_DAHERCMS.SecurePage.Rechange.ECRANPROD.Parametrage
{


    public partial class _default
    {
    }
}
