//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DX_DAHERCMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBSP_TB_MOP
    {
        public int ID_MOP { get; set; }
        public string MOP { get; set; }
        public string LIBELLE_MOP { get; set; }
    }
}
