//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DX_DAHERCMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBSP_TB_Article
    {
        public int IDPartNumber { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> MassZ { get; set; }
        public Nullable<int> Lenght { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<double> Surface { get; set; }
        public Nullable<double> Volume { get; set; }
        public string Materiel { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public string img4 { get; set; }
        public string FINO { get; set; }
        public byte[] imgbi1 { get; set; }
        public byte[] imgbi2 { get; set; }
        public byte[] imgbi3 { get; set; }
        public byte[] imgbi4 { get; set; }
        public Nullable<System.DateTime> DatePicture { get; set; }
        public string UserPicture { get; set; }
        public Nullable<System.DateTime> DateData { get; set; }
        public string UserData { get; set; }
        public string Commentaires { get; set; }
        public string Type { get; set; }
        public string Litige { get; set; }
        public Nullable<double> Mass { get; set; }
        public Nullable<int> MOP { get; set; }
    }
}
